#!/bin/bash

### Run on Jenkins Slave using CLI on Linux Terminal ###

## Java

sudo yum install java-17-openjdk -y
readlink -f $(which java)

cat <<EOF | sudo tee /etc/profile.d/java.sh
export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
export PATH=$PATH:$JAVA_HOME/bin
EOF

source /etc/profile.d/java.sh
echo $JAVA_HOME


## Maven

cd /opt
sudo wget http://mirrors.ibiblio.org/apache/maven/maven-4/4.0.0-rc-5/source/apache-maven-4.0.0-rc-5-src.tar.gz
sudo tar -xvzf apache-maven-4.0.0-rc-5-src.tar.gz
sudo mv apache-maven-4.0.0-rc-5 maven

cat <<EOF | sudo tee /etc/profile.d/maven.sh
export M2_HOME=/opt/maven
export MAVEN_HOME=/opt/maven
export PATH=$PATH:$M2_HOME/bin
EOF

source /etc/profile.d/maven.sh
mvn -version

