---
- hosts: all
  become: yes
  tasks:
    - name: Update apt cache and make sure Vim, Curl and Unzip are installed
      yum:
        name: "{{ item }}"
      loop:
        - vim
        - curl
        - unzip